### ISSUE TITLE
Error after HelpTreeBase setup when using AnalysisBase 21.2.0 

### ISSUE THREAD

**Issue by tmk1808** [UCATLAS/xAODAnaHelpers#974] opened 2017-07-27 13:11 UTC
This error can be reproduced when running xAH_run.py after setting up release 21.2.0
Log and err files are attached

[err_MC.txt](https://github.com/UCATLAS/xAODAnaHelpers/files/1180015/err_MC.txt)
[log_MC.txt](https://github.com/UCATLAS/xAODAnaHelpers/files/1180014/log_MC.txt)

**Comment by kratsg** [comment] 2017-07-27 13:56
Hi, can you run with `"m_msgLevel": "debug"` for BasicEventSelection and see what it's trying to retrieve/complain about?

**Comment by tmk1808** [comment] 2017-07-27 16:35
Hi,
I've added it to the JSON file, but now it's complaining about that line.
[err_MC.txt](https://github.com/UCATLAS/xAODAnaHelpers/files/1180634/err_MC.txt)

Thank you,
Tigran

**Comment by kratsg** [comment] 2017-07-27 16:54
Are you using a python or json config? Are you using master of the repo?

**Comment by tmk1808** [comment] 2017-07-27 16:55
It's the master of the repo and we're using json config files

**Comment by kratsg** [comment] 2017-07-27 18:59
Please update to master of xAH which fixes a bug in JSON configuration
files.

**Comment by tmk1808** [comment] 2017-07-27 19:57
I'm on the latest update, after I sent the mail, you fixed xAH_run.py, thank you, but there is something specific with m_msgLevel, after setting it to an integer (1), it seems to work and the debug lines are printed. This created quite a large log file, I can put it in a public space in afs if it's more convenient.
[err_MC.txt](https://github.com/UCATLAS/xAODAnaHelpers/files/1181086/err_MC.txt)

**Comment by kratsg** [comment] 2017-07-27 21:31
I'm going to definitely need the log. You can upload a file here: https://gist.github.com/ . There might be a residual bug in xAH still for setting `m_msgLevel`

**Comment by kratsg** [comment] 2017-07-27 21:38
FYI, I've updated xAH again to fix the unicode error you saw. You can now do `"m_msgLevel": "debug"` and it should work as expected.

**Comment by tmk1808** [comment] 2017-07-28 06:15
Yes, thank you, now we're back to the original problem, here are the log files
[err_MC.txt](https://github.com/UCATLAS/xAODAnaHelpers/files/1182158/err_MC.txt)
[log_MC.txt](https://github.com/UCATLAS/xAODAnaHelpers/files/1182159/log_MC.txt)

**Comment by kratsg** [comment] 2017-07-31 01:11
What does your JSON configuration look like? It appears you're running BasicEventSelection... twice?

**Comment by jbossios** [comment] 2017-07-31 01:17
This is the JSON file @tmk1808 is using:

[
  { "class": "BasicEventSelection",
    "configs": {
      "m_name": "basicEventSel",
      "m_truthLevelOnly": false,
      "m_applyGRLCut": false,
      "m_GRLxml": "",
      "m_doPUreweighting": false,
      "m_applyPrimaryVertexCut": true,
      "m_vertexContainerName": "PrimaryVertices",
      "m_PVNTrack": 2,
      "m_checkDuplicatesMC": true,
      "m_derivationName": "JETM1Kernel" // Using JETM1 momentarily instead of JETM9
    }
  },

  { "class": "JetCalibrator",
    "configs": {
      "m_calibConfigFullSim": "JES_data2016_data2015_Recommendation_Dec2016_rel21.config",
      "m_name": "jetCalib",
      "m_calibSequence": "JetArea_Residual_EtaJES_GSC",
      "m_sort": true,
      "m_doCleaning": true,
      "m_jetCleanCutLevel": "LooseBad",
      "m_saveAllCleanDecisions": true,
      "m_jetCleanUgly": false,
      "m_inContainerName": "AntiKt4EMTopoJets",
      "m_outContainerName": "AntiKt4EMTopoJets_Nominal",
      "m_jetAlgo": "AntiKt4EMTopo",
      "m_outputAlgo": "AntiKt4EMTopoJets_Nominal_Algo",
      "m_JESUncertConfig": "",
      "m_systName": "",
      "m_JERUncertConfig": ""
    }
  },

  { "class": "JetSelector",
     "configs": {
      "m_inContainerName": "AntiKt4EMTopoJets_Nominal",
      "m_name": "jetSel",
      "m_inputAlgo": "AntiKt4EMTopoJets_Nominal_Algo",
      "m_decorateSelectedObjects": true,
      "m_createSelectedContainer": true,
      "m_outContainerName": "AntiKt4EMTopoJets_Signal",
      "m_outputAlgo":  "AntiKt4EMTopoJets_Signal_Algo",
      "m_cleanJets": false,
      "m_pT_min": 30e3,
      "m_useCutFlow": true
    }
  },

  { "class": "JetSelector",
     "configs": {
      "m_name": "TruthSelector",
      "m_inContainerName": "AntiKt4TruthJets", // Not using TruthWZJets momentarily (JETM1 insteald of JETM9)
      "m_decorateSelectedObjects": true,
      "m_createSelectedContainer": true,
      "m_outContainerName": "AntiKt4TruthWZJets_Signal",
      "m_outputAlgo":  "AntiKt4TruthWZJets_Signal_Algo",
      "m_cleanJets": false,
      "m_pT_min": 30e3,
      "m_useCutFlow": true
    }
  },

  { "class": "TreeAlgo",
     "configs": {
      "m_jetContainerName": "AntiKt4EMTopoJets_Signal",
      "m_name": "treeAlgo",
      "m_jetDetailStr": "kinematic rapidity energy layer clean scales truth",
      "m_truthJetContainerName": "AntiKt4TruthWZJets_Signal",
      "m_truthJetDetailStr": "kinematic rapidity",
      "m_evtDetailStr": "pileup"
    }
  }

]

Cheers

**Comment by kratsg** [comment] 2017-07-31 01:23
Ok, what file is this on? You seem to have a broken file that needs to be reported to PATHelp. The crash is definitely occurring inside a `TEvent::contains<T>` call.

**Comment by kratsg** [comment] 2017-07-31 01:31
Specifically: Attila Kraz., Scott Snyder, and Kerim Suruliz need to be emailed.

**Comment by jbossios** [comment] 2017-07-31 01:36
The files should be fine since are widely use by the JetEtMiss group to derive the MC16 calibrations and we are not retrieving nothing new:
mc16_13TeV.3610*.Pythia8*JZ*W.*JETM1*_r9315_p3141

**Comment by kratsg** [comment] 2017-07-31 02:35
Hi @jbossios,

I can easily reproduce this with a simple `TEvent::contains<T>` call without using xAH. The problem is definitely with the files -- and the segfaults also show this as well. The segfault is occurring because of a `contains` call on an `xAOD::EventInfo_v1` object. Unless mc16 is using `EventInfo_v2` (which I don't think exists), then there is an underlying problem...

Giordon

**Comment by kratsg** [comment] 2017-07-31 02:41
> The files should be fine since are widely use by the JetEtMiss group to derive the MC16 calibrations and we are not retrieving nothing new:
> mc16_13TeV.3610*.Pythia8JZW.JETM1_r9315_p3141

Wait, are these rel21 files or rel20 files? It looks like, from the ptag, you're using the wrong files for release 21... You can't use release 21 on release 20.7 files.

**Comment by kratsg** [comment] 2017-07-31 03:08
> Wait, are these rel21 files or rel20 files? It looks like, from the ptag, you're using the wrong files for release 21... You can't use release 21 on release 20.7 files.

According to AMI, this appears to be produced with `AtlasDerivation_21.0.19.2` so I don't think it's a release mix-up...

**Comment by kratsg** [comment] 2017-07-31 03:27
I've done some extra debugging and I really think there's problems with the files...

```
TBufferFile::CheckByte... ERROR   object of class vector<string> read too few bytes: 2 instead of 83
TBufferFile::CheckByte... ERROR   object of class vector<string> read too few bytes: 2 instead of 78
TBufferFile::CheckByte... ERROR   object of class vector<string> read too few bytes: 2 instead of 87
```

is reported from AthAnalysisBase.

`xAODChecker` reports quite a few errors with the files. Running in AnalysisBase with `kAthena` access mode doesn't work. I'm going to have to report this to PATHelp as I don't think it's a problem with xAH.

**Comment by tmk1808** [comment] 2017-07-31 06:29
Hi,
This can be reproduced for Data as well, e.g. data16_13TeV.003110*.physics_Main.deriv.DAOD_JETM1.r9264_p3083_p3142
So it's not only the MC files, but then these run fine with AnalysisBase 2.6.4

**Comment by kratsg** [comment] 2017-07-31 11:03
> This can be reproduced for Data as well, e.g. data16_13TeV.003110*.physics_Main.deriv.DAOD_JETM1.r9264_p3083_p3142
> So it's not only the MC files, but then both run fine with AnalysisBase 2.6.4

Can you try a non-JETM1 derivation? We need to isolate whether this is a derivation issue or a rel 21 processed file issue.

**Comment by tmk1808** [comment] 2017-07-31 11:15
We get the segfault with the JETM9 data derivation as well. For example:
data16_13TeV:data16_13TeV.*.physics_Main.deriv.DAOD_JETM9.r9264_p3083_p3213
These are produced with AtlasDerivation_21.0.19.6

**Comment by kratsg** [comment] 2017-07-31 11:17
Can you try a SUSY derivation? JET derivations are very similar.

**Comment by tmk1808** [comment] 2017-07-31 11:48
Can you let me know what the name of the SUSY derivation framework is? I'm getting this:
`(virtual EL::StatusCode BasicEventSelection::fileExecute()): No CutBookkeeper corresponds to the selected Derivation Framework algorithm name. Check it with your DF experts! Aborting.`
with the data16_13TeV.*.physics_Main.deriv.DAOD_SUSY10.r9264_p3083_p3213 datasets

**Comment by tmk1808** [comment] 2017-07-31 12:46
It's still crashing with a SUSY derivation.
[log_Data.txt](https://github.com/UCATLAS/xAODAnaHelpers/files/1187558/log_Data.txt)

**Comment by kratsg** [comment] 2017-07-31 13:12
> (virtual EL::StatusCode BasicEventSelection::fileExecute()): No CutBookkeeper corresponds to the selected Derivation Framework algorithm name. Check it with your DF experts! Aborting.

This crash is just due to the derivation name you're setting in BasicEventSelection. I'm now unable to reproduce the segfault after cleaning and remaking. Can you try removing the `build`, making it again, and doing the `cmake/make` commands again? I wonder if you're still able to get it.

**Comment by tmk1808** [comment] 2017-07-31 15:00
After cleaning and rebuilding the code, there is still the segfault, but not much information to debug.
Here is the log:
[log_Data.txt](https://github.com/UCATLAS/xAODAnaHelpers/files/1187938/log_Data.txt)

**Comment by beojan** [comment] 2017-08-02 13:38
I get the same error with an EXOT8 data17 file.

[xAH_run.log.txt](https://github.com/UCATLAS/xAODAnaHelpers/files/1194012/xAH_run.log.txt)

**Comment by kratsg** [comment] 2017-08-02 13:48
@beojan I'm not 100% sure that's the same error, but it does look similar. For everyone, this particular issue most likely came up because of the update in the ROOT version and then being propagated. In particular, this is a bug that is now reported [in ROOT JIRA](https://sft.its.cern.ch/jira/browse/ROOT-8936) and described in this [email thread](https://groups.cern.ch/group/hn-atlas-PATHelp/Lists/Archive/Flat.aspx?RootFolder=%2Fgroup%2Fhn%2Datlas%2DPATHelp%2FLists%2FArchive%2FSegfaultsCheckByte%20errors%20in%2021%2E2%2E0%2CAB&FolderCTID=0x0120020084D7E80CB0C3394A8D54EF07C309B044).

There is a fix in the offline software that was merged in ~20 minutes ago, see this [commit](https://gitlab.cern.ch/atlas/athena/commit/995a3d2b6a5261c5328827f72214d531e09bea4a) for information. I will update again with instructions on setting up the correct nightly that contains this commit so you can try again and see if the error resolves itself.

**Comment by kratsg** [comment] 2017-08-04 02:05
@tmk1808 , @jbossios , @beojan  (and @jdandoy ) -- this segfault seems to go away with the [commit to atlas/athena](https://gitlab.cern.ch/atlas/athena/commit/995a3d2b6a5261c5328827f72214d531e09bea4a) I mentioned in my previous message.

Please try using:

```
asetup AnalysisBase,21.2,2017-08-03T2258
```
or, overwrite your top-level `CMakeLists.txt`:

```
asetup AnalysisBase,21.2,2017-08-03T2258,here
```

and retry your code again. If this seems to resolve the issue, I suspect we can call this fixed. If this fixes the issue for you, gimme a `+1` on this comment, otherwise, please comment again if you're still running into problems. If I hear nothing back in a week, I'll preemptively close this issue as I am able to run previously-broken-code from provided `json` config.

------------------

Now works:
```
root [0] 
Attaching file submitDir/data-tree/mc16_13TeV.root as _file0...
.(TFile *) 0x1fc1810
root [1] .ls
TFile**		submitDir/data-tree/mc16_13TeV.root	
 TFile*		submitDir/data-tree/mc16_13TeV.root	
  KEY: TDirectoryFile	treeAlgo;1	treeAlgo
root [2] treeAlgo->ls()
TDirectoryFile*		treeAlgo	treeAlgo
 KEY: TTree	nominal;1	nominal
root [3] treeAlgo->cd()
(Bool_t) true
root [4] .ls
TDirectoryFile*		treeAlgo	treeAlgo
 KEY: TTree	nominal;1	nominal
root [5] nominal->GetEntries()
(Long64_t) 100
root [6] .q
```

**Comment by tmk1808** [comment] 2017-08-04 09:04
@kratsg Can confirm that it's working.

**Comment by beojan** [comment] 2017-08-04 09:36
Works for me too

**Closed** 2017-08-04 12:09 UTC
Labels: bug, wontfix
