### ISSUE TITLE
Error 'JETIDBDTLOOSENOTTIGHT' is not a member of 'TauAnalysisTools'

### ISSUE THREAD

**Issue by HenryDayHall** [UCATLAS/xAODAnaHelpers#1521] opened 2022-02-07 10:33 UTC
Apologies in advance for being pretty naive about a lot of things, I'm hoping that you can give me a few pointers in the right direction. I'm supposed to be updating some code to work with a more recent version of athena, and this code also requires xAODAnaHelpers. Currently, when I try to compile I get the error;

```
Error 'JETIDBDTLOOSENOTTIGHT' is not a member of 'TauAnalysisTools'
```

and indeed, `JETIDBDTLOOSENOTTIGHT` was removed from recent versions of athena, [in this commit](https://gitlab.cern.ch/atlas/athena/-/commit/53a1b84375b6687e6fc31c9bdf02c83d3aa3cc9a) (only a month ago). But then some of the issues posted here seem to imply that athena is not needed for this package, [like this one](https://github.com/UCATLAS/xAODAnaHelpers/issues/1421). So I'm not sure I have properly understood the relationship between this package and athena. Perhaps there should be a way to update athena and not hit this issue?

Interestingly, I can make xAODAnaHelpers on it's own with the same version of athena that breaks it in conjunction with my code. It doesn't seem to matter that xAODAnaHelpers is referencing `JETIDBDTLOOSENOTTIGHT` and that doesn't exist anymore until I combine xAODHelpers with additional code. But [this file](https://github.com/UCATLAS/xAODAnaHelpers/blob/r22/master/Root/TauSelector.cxx) is certainly using  `JETIDBDTLOOSENOTTIGHT`, so I don't understand why that works.

Any wisdom you can offer is gratefully received.

**Comment by jbossios** [comment] 2022-02-07 10:52
I guess that working point is not available anymore (on R22). Which seems to be confirmed by looking at this:
https://gitlab.cern.ch/atlas/athena/-/blob/master/PhysicsAnalysis/TauID/TauAnalysisTools/doc/README-TauSelectionTool.rst

From that page, it seems only these WPs are supported in R22:

JETIDNONE
JETIDRNNVERYLOOSE
JETIDRNNLOOSE
JETIDRNNMEDIUM
JETIDRNNTIGHT

Most likely, no one yet tested xAH on R22 with taus. Would you mind removing all non-supported WPs in the file below and test again?

https://github.com/UCATLAS/xAODAnaHelpers/blob/r22/master/Root/TauSelector.cxx

If that solves it, could you please make a PR to fix this?

**Comment by HenryDayHall** [comment] 2022-02-07 11:36
Many thanks, making that change does indeed get rid of this error. 

I now get a few more errors that probably run in the same vein;
```
error: 'SFEleOLRHadTau' is not a member of 'TauAnalysisTools'                                                        
```

So would it be best if I try to fix anything that looks related and then make a PR with all the related updates?

**Comment by jbossios** [comment] 2022-02-07 11:37
Great! Yes, that sounds awesome. Thanks a lot!

**Comment by HenryDayHall** [comment] 2022-02-07 17:00
Still need to test it but have a draft for this now; https://github.com/UCATLAS/xAODAnaHelpers/pull/1522

**Comment by jbossios** [comment] 2022-03-04 10:09
Closing issue since PR with fixes was merged.

**Closed by jbossios** 2022-03-04 10:09 UTC
