### ISSUE TITLE
Running in Docker (GitLab CI)

### ISSUE THREAD

**Issue by beojan** [UCATLAS/xAODAnaHelpers#1168] opened 2018-02-21 16:52 UTC
My project builds correctly with the normal clone into a directory beside xAODAnaHelpers workflow, but when running on GitLab CI using the Docker image, I get the error:

```
/builds/OxfordATLASExotics/XhhOxford/Root/ApplyJetSelection.cxx:8:42: fatal error: xAODAnaHelpers/HelperClasses.h: No such file or directory
 #include "xAODAnaHelpers/HelperClasses.h"
```

Is there a particular configuration change needed to make this work?

**Comment by kratsg** [comment] 2018-02-21 16:59
Did you make sure to set up the scripts? When you run interactively, you see this message

```
                          __  __
                          \ \/ /
                           >  <
           _    _  _____  /_/\_\______ _                _____
          | |  | |/ ____|   /\|__   __| |        /\    / ____|
          | |  | | |       /  \  | |  | |       /  \  | (___
          | |  | | |      / /\ \ | |  | |      / /\ \  \___ \
          | |__| | |____ / ____ \| |  | |____ / ____ \ ____) |
           \____/ \_____/_/    \_\_|  |______/_/    \_\_____/
                         | |  | |
                         | |__| |
                         |  __  |
                         | |  | |
                         |_|  |_|

This is a self-contained ATLAS ASG release image with xAODAnaHelpers. Your
.bashrc should already execute the necessary scripts to set up the analysis
base release as well as xAODAnaHelpers. View our online documentation here:

      https://xaodanahelpers.readthedocs.io/en/master/

To set up xAODAnaHelpers + the analysis release of the image, please execute:

      source /home/atlas/xAODAnaHelpers_setup.sh

To set up *only* the analysis release of the image, please execute:

      source /home/atlas/release_setup.sh

Configured GCC from: /opt/lcg/gcc/6.2.0/x86_64-slc6
Configured AnalysisBase from: /usr/AnalysisBase/21.2.13/InstallArea/x86_64-slc6-gcc62-opt
Configured xAODAnaHelpers from: /usr/xAODAnaHelpers/903fd1016571343250fe27c47768e6b2df3f0fc3/InstallArea/x86_64-slc6-gcc62-opt
```

So you should run `source /home/atlas/xAODAnaHelpers_setup.sh` first to set up the environment for CMake to find the files.

**Comment by beojan** [comment] 2018-02-21 17:02
I don't see the banner, but I do get
```
$ source /home/atlas/xAODAnaHelpers_setup.sh
Configured GCC from: /opt/lcg/gcc/6.2.0/x86_64-slc6
Configured AnalysisBase from: /usr/AnalysisBase/21.2.13/InstallArea/x86_64-slc6-gcc62-opt
Configured xAODAnaHelpers from: /usr/xAODAnaHelpers/96a53cd2c9d589b5da1b1b1e78e73a5b5f368ca2/InstallArea/x86_64-slc6-gcc62-opt
```

**Comment by kratsg** [comment] 2018-02-21 17:02
How are you running interactively? 

```
docker run -it --rm ucatlas/analysisbase:21.2.13-latest bash
```

shows me the banner. It's part of the "message of the day".

**Comment by kratsg** [comment] 2018-02-21 17:03
Can you link me to your GitLab CI? But adding the source script in there should make the libraries findable.

**Comment by beojan** [comment] 2018-02-21 17:04
Ah, ok. Singularity has a policy of "you are the same user inside the container as outside", so `.bashrc` doesn't run.

The CI at https://gitlab.cern.ch/OxfordATLASExotics/XhhOxford/blob/master/.gitlab-ci.yml
The output is https://gitlab.cern.ch/OxfordATLASExotics/XhhOxford/-/jobs/1044116

**Comment by kratsg** [comment] 2018-02-21 17:13
I can't see it. Make sure you add `atlas-current-physicists` as a reporter.

**Comment by kratsg** [comment] 2018-02-21 17:17
> Ah, ok. Singularity has a policy of "you are the same user inside the container as outside", so .bashrc doesn't run.

In the meantime, I'll file an issue so we can get the motd running for sure. In this case, it's a matter of adding a script to `/etc/profile.d/*.sh` to do this. Thanks for reporting that!

**Comment by lukasheinrich** [comment] 2018-02-21 17:29
@beojan are you running singularity on LXPLUS? I'd be interested to get this to work on singularity generally (for ATLAS images), so having someone to test with would be useful

**Comment by beojan** [comment] 2018-02-22 09:15
`atlas-current-physicists` now has reporter access.

@lukasheinrich I'm running Singularity on my laptop, actually, though I doubt there are any significant differences compared to lxplus (with the exception that creating images requires sudo access so it can'y be done on lxplus).

**Comment by ntadej** [comment] 2018-02-22 14:40
@lukasheinrich, I managed to run the docker image inside singularity on our institute PCs directly from gitlab-registry.cern.ch.
```
singularity shell docker://gitlab-registry.cern.ch/atlas-ssmultilep/analysiscode:master
```

The image would need to be updated a bit though:
 - MOTD is not loaded
 - one needs to navigate to /home/atlas to get to the setup scripts
 - analysis_release_setup.sh is not found as `$HOME` is different that `/home/atlas`

I didn't manage to get it running on lxplus though. Our version of singularity is 2.4.2-dist and on lxplus it's 2.2.1.

**Comment by kratsg** [comment] 2018-02-22 14:47
> @lukasheinrich, I managed to run the docker image inside singularity on our institute PCs directly from gitlab-registry.cern.ch.
> 
> singularity shell docker://gitlab-registry.cern.ch/atlas-ssmultilep/analysiscode:master

Are you using xAH docker images as part of your CI? You might not be (not sure). 

> MOTD is not loaded

I can fix this in the xAH docker images, see #1169 .

> one needs to navigate to /home/atlas to get to the setup scripts
> analysis_release_setup.sh is not found as $HOME is different that /home/atlas

This can be fixed similar to #1169 as well.

**Comment by kratsg** [comment] 2018-02-22 14:48
> Is there a particular configuration change needed to make this work?

@beojan I'm able to reproduce this now. It seems like nobody's been using our docker images for their builds yet... so no wonder it didn't get caught! I've sent an email asking Attila why CMake is not picking up the libraries which clearly exist in the image.

**Comment by beojan** [comment] 2018-02-22 14:53
The easiest fix for @ntadej's third point is to use the full path (`/home/atlas/analysis_relese_setup.sh`).
On the other hand, it might be better to just set $HOME to `/home/atlas` in `/etc/profile` (in which case `.bashrc` should also run, I think).

**Comment by kratsg** [comment] 2018-02-22 14:54
> On the other hand, it might be better to just set $HOME to /home/atlas in /etc/profile (in which case .bashrc should also run, I think).

not a good idea. This is dangerous in singularity since the user is different. The fix would be to have the scripts run in `/etc/profile.d/` instead.

**Comment by beojan** [comment] 2018-02-22 14:57
The files in /home/atlas are owned by the local user in Singularity.

The other issue is that if $HOME isn't reset, all your local config files get picked up (e.g. the local .bashrc and .vimrc).

**Comment by ntadej** [comment] 2018-02-22 15:07
> Are you using xAH docker images as part of your CI? You might not be (not sure).

No, as I have xAH as a submodule, I use base atlas images.

**Comment by kratsg** [comment] 2018-03-16 16:27
The workaround right now (this got merged in: https://gitlab.cern.ch/atlas/atlasexternals/merge_requests/264) on older images is to do two things:

```bash
find_packages(xAODAnaHelpers)
```

in your top-level CMakeLists.txt

and set

```bash
export xAODAnaHelpers_VERSION=$AnalysisBase_VERSION
```

or whatever the appropriate version is here.

**Closed** 2018-03-16 16:27 UTC
