### ISSUE TITLE
Master xAH_run Crashes immediately 

### ISSUE THREAD

**Issue by johnda102** [UCATLAS/xAODAnaHelpers#874] opened 2017-04-24 14:25 UTC
Hi All, 

 I updated to master and run a command that worked previously and see:

Anyone else run into this too ?
Any idea what is broken in the lastests commits ?

 > xAH_run.py  --file mc16_13TeV.410000.PowhegPythiaEvtGen_P2012_ttbar_hdamp172p5_nonallhad.merge.AOD.e3698_s2997_r8903_r8906  --inputRucio     --config StudyTrigTracks/scripts/config_SingleJetSelection.py     -f  --submitDir DebugTuning --nevents 1000 direct
[2017-04-24 09:23:34,457][INFO   ]  ======================================== (timing.py:17)
[2017-04-24 09:23:34,457][INFO   ]  414734:23:34.457-Start Program (timing.py:18)
[2017-04-24 09:23:34,457][INFO   ]  ======================================== (timing.py:21)
[2017-04-24 09:23:34,457][INFO   ]  removing DebugTuning (xAH_run.py:269)
[2017-04-24 09:23:36,081][ERROR  ]  --------------------
An exception was caught! (xAH_run.py:672)
Traceback (most recent call last):
  File "/share/t3data3/johnda/StudyTrigTracks/RootCoreBin/bin/x86_64-slc6-gcc49-opt/xAH_run.py", line 326, in <module>
    raise OSError("It doesn't seem like '{0:s}' exists. Did you set up your CMake environment correctly? (Hint: source 'build/{1:s}/setup.sh)".format(cmake_setup, arch))
OSError: It doesn't seem like 'WorkDir_SET_UP' exists. Did you set up your CMake environment correctly? (Hint: source 'build/<arch>/setup.sh)
[2017-04-24 09:23:36,108][INFO   ]  ======================================== (timing.py:17)
[2017-04-24 09:23:36,108][INFO   ]  414734:23:36.108-End Program (timing.py:18)
[2017-04-24 09:23:36,108][INFO   ]  Elapsed time: 0:00:01.651 (timing.py:20)
[2017-04-24 09:23:36,108][INFO   ]  ======================================== (timing.py:21)

**Comment by kratsg** [comment] 2017-04-24 14:35
@johnda102 what release are you using?

**Comment by johnda102** [comment] 2017-04-24 14:37
release = --obj-release /cvmfs/atlas.cern.ch/repo/sw/ASG/AnalysisBase/2.5.1/RootCore

> echo $ROOTCORE_RELEASE_SERIES
25

**Comment by johnda102** [comment] 2017-04-24 14:38
not in athena

**Comment by kratsg** [comment] 2017-04-24 14:39
@johnda102 why are you using 2.5.X? It's not recommended by anyone (including ASG?). Isn't that also CMake-based? The problem is that both 2.5.X and 2.6.X set `$ROOTCORE_RELEASE_SERIES` to `25`.

**Comment by johnda102** [comment] 2017-04-24 14:40
I had to run on rel21 samples before 2.6 was available. 
Ill try 2.6.X

**Comment by kratsg** [comment] 2017-04-24 14:43
Please do. We have documented instructions and 2.6.X is the official for rel21.

**Comment by johnda102** [comment] 2017-04-24 14:43
> rcSetup -r
Available releases are:
asgType=stable (at /cvmfs/atlas.cern.ch/repo/sw/ASG):
 SUSY: 	1.0.0 1.0.1 1.0.2 1.0.3 1.0.4 1.0.5 1.0.6 1.0.7
  	2.3.12 2.3.14 2.3.15 2.3.15a 2.3.18b 2.3.19 2.3.21 2.3.23 2.3.24
  	2.3.24a 2.3.26 2.3.28 2.3.30 2.3.31 2.3.32 2.3.32a 2.3.33 2.3.33a
  	2.3.34 2.3.35 2.3.36a 2.3.37 2.3.37a 2.3.38a 2.3.38b 2.3.39 2.3.40
  	2.3.41 2.3.42 2.3.44a 2.3.45 2.3.46 2.3.48
 Top: 	1.0.0 1.1.0 1.2.0 1.3.0 1.4.0 1.5.0 1.5.1 1.6.0 1.6.1 1.7.0 1.7.1 1.8.0
  	1.8.1 1.9.0 1.9.1 1.10.0 1.10.1 1.11.0 1.12.0 1.13.0
  	2.0.0 2.0.1 2.0.15 2.0.16 2.0.23 2.0.23a 2.0.24 2.0.27
  	2.1.28 2.1.29 2.1.31 2.1.32 2.1.33 2.3.11 2.3.12 2.3.13 2.3.15a 2.3.15b
  	2.3.17 2.3.17a 2.3.18 2.3.20 2.3.23a 2.3.23b 2.3.23c 2.3.26 2.3.30
  	2.3.33 2.3.34 2.3.35 2.3.37 2.3.39 2.3.40 2.3.41 2.3.44 2.3.45a 2.3.49
  	2.3.51 2.3.52 2.4.5 2.4.6 2.4.10 2.4.12 2.4.13 2.4.14 2.4.15 2.4.16
  	2.4.17 2.4.18 2.4.19 2.4.21 2.4.22 2.4.22a 2.4.23 2.4.24 2.4.25 2.4.26
  	2.4.27 2.4.28a 2.4.29 2.4.30
 Base: 	1.0.0 1.0.1 1.1.0 1.2.0 1.3.0 1.4.0 1.5.0 1.5.1 1.5.2 1.5.3 1.5.4 1.5.5
  	1.5.6 1.5.7 1.5.8 1.5.9 1.5.10 1.5.11 1.5.13 1.5.14
  	2.0.0 2.0.1 2.0.2 2.0.3 2.0.4 2.0.5 2.0.6 2.0.7 2.0.8 2.0.9 2.0.10
  	2.0.11 2.0.12 2.0.13 2.0.14 2.0.15 2.0.16 2.0.17 2.0.18 2.0.19 2.0.20
  	2.0.21 2.0.22 2.0.23 2.0.24 2.0.25 2.0.26 2.0.27
  	2.1.0 2.1.11 2.1.19 2.1.21 2.1.22 2.1.23 2.1.24 2.1.25 2.1.26 2.1.27
  	2.1.28 2.1.29 2.1.30 2.1.31 2.1.32 2.1.32-MAC 2.1.33 2.1.34 2.1.34-MAC
  	2.1.35 2.1.36 2.2.0 2.2.1 2.2.2 2.2.3 2.2.4 2.2.5 2.3.0 2.3.1 2.3.2
  	2.3.3 2.3.4 2.3.5 2.3.6 2.3.7 2.3.8 2.3.9 2.3.10 2.3.11 2.3.11-MAC
  	2.3.12 2.3.13 2.3.13-MAC 2.3.14 2.3.15 2.3.15-MAC 2.3.16 2.3.16-MAC
  	2.3.17 2.3.17-MAC 2.3.18 2.3.18-MAC 2.3.19 2.3.19-MAC 2.3.20 2.3.20-MAC
  	2.3.21 2.3.21-MAC 2.3.22 2.3.22-MAC 2.3.23 2.3.23-MAC 2.3.24 2.3.24-MAC
  	2.3.25 2.3.25-MAC 2.3.26 2.3.28 2.3.28-MAC 2.3.29 2.3.29-MAC 2.3.30
  	2.3.30-MAC 2.3.31 2.3.31-MAC 2.3.32 2.3.32-MAC 2.3.33 2.3.34 2.3.35
  	2.3.36 2.3.37 2.3.38 2.3.39 2.3.40 2.3.41 2.3.42 2.3.43 2.3.44 2.3.45
  	2.3.46 2.3.48 2.3.49 2.3.50 2.3.51 2.3.52 2.3.53 2.4.3 2.4.4 2.4.5
  	2.4.6 2.4.7 2.4.8 2.4.9 2.4.10 2.4.11 2.4.12 2.4.13 2.4.14 2.4.15
  	2.4.16 2.4.17 2.4.18 2.4.19 2.4.20 2.4.21 2.4.22 2.4.22hi 2.4.23
  	2.4.23hi 2.4.24 2.4.24hi 2.4.25 2.4.25hi 2.4.26 2.4.27 2.4.27hi 2.4.28
  	2.4.28hi 2.4.29 2.4.29hi 2.4.30 2.4.30hi 2.5.0 2.5.1

**Comment by johnda102** [comment] 2017-04-24 14:45
still seems like 2.5.1 is the latest base thats availible

**Comment by kratsg** [comment] 2017-04-24 14:45
https://xaodanahelpers.readthedocs.io/en/master/Installing.html#cmake-based-rootcore-2-5-x - follow the instructions here. You need to use `asetup` for rel21 releases now. `rcSetup` is being deprecated.

**Comment by johnda102** [comment] 2017-04-24 14:50
hmm ok 

How come that havent put any of this on the ATLAS web pages:
eg:
https://twiki.cern.ch/twiki/bin/view/AtlasProtected/AnalysisRelease#AnalysisBase

**Comment by kratsg** [comment] 2017-04-24 14:51
My guess is that ASG needs to document things better. There are not many obvious things, eg:

> Note you can also setup eventloop releases using asetup: asetup AnalysisBase,2.3.30 is equivalent to rcSetup Base,2.3.30.

so I'm not sure why this isn't consistent or clear enough... but it's in our documentation.

**Comment by kratsg** [comment] 2017-04-24 19:42
Fixed in latest.

**Closed by kratsg** 2017-04-24 19:42 UTC
