### ISSUE TITLE
Question on xAH_run.py minimal example on docs, direct driver

### ISSUE THREAD

**Issue by urania277** [UCATLAS/xAODAnaHelpers#423] opened 2015-12-21 16:12 UTC
this time I'm trying to run an extremely minimal example locally following but it'm not finding it as :beers: as in the tutorial. 

The TLABasicConfig.json below is only the BasicEventSelection straight from https://xaodanahelpers.readthedocs.org/en/latest/UsingUs.html#a-simple-plotting-example

I can't seem to get out of the exception when trying to run on two xAODs that I have in my local directory (a single file would not work). Debugging would probably require more experience with SampleHandler, so help from someone who managed to run this locally would be appreciated. 

MacBook-Pro-7:TLARun urania277$ xAH_run.py --files file1.root file2.root --config TLABasicConfig.json -f -vv direct
!========================================
402976:04:16.147-Start Program
!========================================

removing submitDir
loading packages
xAOD::Init                INFO    Environment initialised for data access
creating new sample handler
		Adding samples using scanDir
SampleHandler:/Users/urania277/Work/ATLAS/sw/releases/AnalysisBase/2.3.38/SampleHandler/Root/SampleHandler.cxx:149:exception: can't add sample of name TLARun
a sample with that name already exists
old sample:
Sample:name=TLARun,tags=()
file:///Users/urania277/Work/ATLAS/sw/projects/TLACode/TLARun/file1.root

new sample:
Sample:name=TLARun,tags=()
file:///Users/urania277/Work/ATLAS/sw/projects/TLACode/TLARun/file2.root

SampleHandler:/Users/urania277/Work/ATLAS/sw/releases/AnalysisBase/2.3.38/SampleHandler/Root/DiskList.cxx:65:exception: already finished processing list
!--------------------
An exception was caught!
Traceback (most recent call last):
  File "/Users/urania277/Work/ATLAS/sw/projects/TLACode/RootCoreBin/bin/generic/xAH_run.py", line 328, in <module>
    ROOT.SH.scanDir(sh_all, sh_list, fname_base, os.path.basename(sample_dir))
TypeError: none of the 3 overloaded methods succeeded. Full details:
  void SH::scanDir(SH::SampleHandler& sh, SH::DiskList& list, const string& pattern = "*.root*", const string& samplePattern = "*", const string& samplePostfix = "") =>
    SampleHandler:/Users/urania277/Work/ATLAS/sw/releases/AnalysisBase/2.3.38/SampleHandler/Root/DiskList.cxx:65:exception: already finished processing list (C++ exception)
  void SH::scanDir(SH::SampleHandler& sh, const string& dir) =>
    takes at most 2 arguments (4 given)
  void SH::scanDir(SH::SampleHandler& sh, const string& dir, const string& prefix) =>
    takes at most 3 arguments (4 given)

!========================================
402976:04:19.451-End Program
Elapsed time: 0:00:03.303
!========================================

**Comment by kratsg** [comment] 2015-12-21 16:23
This is telling you the error:

```
SampleHandler:/Users/urania277/Work/ATLAS/sw/releases/AnalysisBase/2.3.38/SampleHandler/Root/SampleHandler.cxx:149:exception: can't add sample of name TLARun
a sample with that name already exists
old sample:
Sample:name=TLARun,tags=()
file:///Users/urania277/Work/ATLAS/sw/projects/TLACode/TLARun/file1.root

new sample:
Sample:name=TLARun,tags=()
file:///Users/urania277/Work/ATLAS/sw/projects/TLACode/TLARun/file2.root

```

Try running

```
xAH_run.py --files "file*.root" --config TLABasicConfig.json -f -vv direct```

**Comment by urania277** [comment] 2015-12-21 18:14
Hmm, I got back to the same error as not being able to run with one file only...error message below. Also I'm not sure going through git comments is is the best way to debug, let me know if I should post problems elsewhere. I appreciate the support though!

MacBook-Pro-7:TLARun urania277$ xAH_run.py --files "file*.root" --config TLABasicConfig.json -f -vv direct
!========================================
402978:11:17.601-Start Program
!========================================

removing submitDir
loading packages
xAOD::Init                INFO    Environment initialised for data access
creating new sample handler
		Adding samples using scanDir
	1 different dataset(s) found
!--------------------
An exception was caught!
Traceback (most recent call last):
  File "/Users/urania277/Work/ATLAS/sw/projects/TLACode/RootCoreBin/bin/generic/xAH_run.py", line 333, in <module>
    for dataset in sh_all:
TypeError: iter() returned non-iterator of type '__wrap_iter<SH::Sample*const*>'

!========================================
402978:11:24.293-End Program
Elapsed time: 0:00:06.691
!========================================

**Comment by kratsg** [comment] 2015-12-21 18:17
That looks like RootCore isn't linking to python correctly on your computer. Or at least, I don't understand why it's returning a non-iterator... Comment out these lines in your script first: https://github.com/UCATLAS/xAODAnaHelpers/blob/master/scripts/xAH_run.py#L332-L334

and re-run. Although the fact that it's returning that seems to be very screwy. I'll ask Nils.

**Comment by urania277** [comment] 2015-12-21 18:35
All good now (docs need a tiny change: m_ApplyGRL -> m_ApplyGRLCut), thanks @kratsg for the help and for asking Nils. I won't submit DQ2 jobs from the laptop as I'm just testing changes locally, I'll leave it to you to close this if you think we can just follow up on the hypernews.

**Comment by kratsg** [comment] 2015-12-21 18:38
> All good now (docs need a tiny change: m_ApplyGRL -> m_ApplyGRLCut)

Where in the docs? Feel free to submit a PR for that.

**Comment by kratsg** [comment] 2015-12-21 18:38
> I won't submit DQ2 jobs from the laptop as I'm just testing changes locally, I'll leave it to you to close this if you think we can just follow up on the hypernews.

We'll close it when the issue is resolved with Nils.

**Comment by kratsg** [comment] 2016-01-21 05:35
I'll close this for now. Seems to be mostly resolved :)

**Closed by kratsg** 2016-01-21 05:35 UTC
